#!/usr/bin/env python3
"""pvscan -- read-only inventory of what AI agents in a log can do.

Single file. No installation, no dependencies beyond the Python standard
library, no network access. It reads the paths you give it and writes
nothing except the report you ask for.

    python3 pvscan.py ~/.claude/projects/
    python3 pvscan.py session.jsonl --json report.json
    python3 pvscan.py ~/.claude/projects/ --dry-run    # list files, read none

Built from privatevault-agent-dna @ b7d89f3 on 2026-08-04.
Generated by tools/build_pvscan_standalone.py -- edit the sources, not this.

PrivateVault AI. Read it before you run it; that is the point of one file.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Iterator
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
import argparse
import csv as _csv
import io
import json
import re
import sqlite3
import sys


# ==================================================================
# from agent_dna/trace.py
# ==================================================================


@dataclass
class AgentAction:
    """A single action an agent attempted (or took) at runtime."""

    agent_id: str
    capability: str
    timestamp: float
    arguments: dict[str, Any] = field(default_factory=dict)
    context: dict[str, Any] = field(default_factory=dict)
    evidence: dict[str, Any] = field(default_factory=dict)
    request_id: str | None = None  # correlation id from the originating request
    outcome: str = "ok"  # "ok" | "error" | "blocked"

    def __post_init__(self) -> None:
        if not self.agent_id:
            raise ValueError("AgentAction.agent_id is required")
        if not self.capability:
            raise ValueError("AgentAction.capability is required")


@dataclass
class ExecutionTrace:
    """An ordered sequence of actions for one agent run / session."""

    agent_id: str
    actions: list[AgentAction] = field(default_factory=list)

    def add(self, action: AgentAction) -> ExecutionTrace:
        if action.agent_id != self.agent_id:
            raise ValueError(
                f"action.agent_id {action.agent_id!r} != trace.agent_id {self.agent_id!r}"
            )

        self.actions.append(action)
        return self

    @property
    def capabilities(self) -> list[str]:
        return [a.capability for a in self.actions]

    def __len__(self) -> int:
        return len(self.actions)


# ==================================================================
# from agent_dna/scan/ingest.py
# ==================================================================

FORMATS = (
    "auto",
    "mcp",
    "openai",
    "anthropic",
    "claude_code",
    "adr",
    "generic",
    "csv",
    "sqlite",
)

# Keys we accept for each required field, in priority order. Real logs
# disagree about names; this is the whole of the flexibility on offer.
_AGENT_KEYS = (
    "agent_id",
    "agentId",
    "agent",
    "actor_id",
    "actor",
    "session_id",
    "sessionId",
    "run_id",
    "runId",
)
_CAPABILITY_KEYS = (
    "capability",
    "tool",
    "tool_name",
    "toolName",
    "name",
    "function",
    "function_name",
    "action",
    "verb",
    "method",
)
_TIMESTAMP_KEYS = (
    "timestamp",
    "ts",
    "time",
    "created_at",
    "createdAt",
    "start_time",
    "startTime",
    "@timestamp",
)
_ARGUMENT_KEYS = (
    "arguments",
    "args",
    "input",
    "inputs",
    "parameters",
    "params",
)
_REQUEST_KEYS = ("request_id", "requestId", "id", "call_id", "callId")

_MAX_RAW_ECHO = 160


@dataclass(frozen=True)
class SkippedRow:
    """A line that could not become an action, and why."""

    line_no: int
    reason: str
    raw: str

    def to_dict(self) -> dict[str, Any]:
        return {"line_no": self.line_no, "reason": self.reason, "raw": self.raw}


@dataclass
class IngestResult:
    actions: list[AgentAction] = field(default_factory=list)
    skipped: list[SkippedRow] = field(default_factory=list)
    source_format: str = "unknown"
    source_path: str = ""
    lines_read: int = 0

    @property
    def understood(self) -> int:
        return len(self.actions)

    @property
    def coverage(self) -> float:
        """Fraction of non-blank lines that became actions. Reported
        verbatim: a scan over a log we only half understood is worth
        exactly half as much, and the operator should be told so."""
        total = len(self.actions) + len(self.skipped)
        return (len(self.actions) / total) if total else 0.0

    def skip_reasons(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for row in self.skipped:
            counts[row.reason] = counts.get(row.reason, 0) + 1
        return dict(sorted(counts.items(), key=lambda kv: -kv[1]))

    def agents(self) -> list[str]:
        return sorted({a.agent_id for a in self.actions})

    def time_span(self) -> tuple[float, float] | None:
        if not self.actions:
            return None
        stamps = [a.timestamp for a in self.actions]
        return (min(stamps), max(stamps))


# ---------------------------------------------------------------------
# field coercion
# ---------------------------------------------------------------------


def _first(obj: dict[str, Any], keys: tuple[str, ...]) -> Any:
    for k in keys:
        if k in obj and obj[k] not in (None, ""):
            return obj[k]
    return None


def parse_timestamp(value: Any) -> float | None:
    """Epoch seconds, epoch millis, or ISO 8601. Returns None rather
    than a fallback -- an action with an invented time would silently
    corrupt every rate and window calculation downstream."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        ts = float(value)
        # Heuristic only for the magnitude, never for existence:
        # anything past year ~2286 in seconds is milliseconds.
        if ts > 1e11:
            ts /= 1000.0
        return ts if ts > 0 else None
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            return parse_timestamp(float(text))
        except ValueError:
            pass
        cleaned = text.replace("Z", "+00:00")
        try:
            dt = datetime.fromisoformat(cleaned)
        except ValueError:
            return None
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=UTC)
        return dt.timestamp()
    return None


def _coerce_arguments(value: Any) -> dict[str, Any]:
    """Tool arguments arrive as a dict or as a JSON string. A string
    that will not parse is kept under a reserved key rather than
    discarded -- it may be the only record of what was attempted."""
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            return {"_raw": value}
        return parsed if isinstance(parsed, dict) else {"_value": parsed}
    if value is None:
        return {}
    return {"_value": value}


def _normalize_capability(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    cap = value.strip()
    return cap or None


_DENIED = {
    "denied",
    "deny",
    "refused",
    "refuse",
    "rejected",
    "reject",
    "declined",
    "decline",
    "blocked",
    "block",
    "forbidden",
    "denied_by_policy",
    "policy_denied",
    "not_permitted",
}
_ERRORED = {"error", "fail", "failed", "failure", "exception", "timeout"}
_ALLOWED = {"ok", "allowed", "allow", "success", "succeeded", "completed"}


def _normalize_outcome(value: Any) -> str:
    """Map a log outcome onto ok/error/blocked. An unrecognised value
    is reported as unknown, never assumed benign."""
    if value is None:
        return "ok"
    t = str(value).strip().lower()
    if t in _DENIED:
        return "blocked"
    if t in _ERRORED:
        return "error"
    if t in _ALLOWED:
        return "ok"
    return "unknown"


def _build_action(
    obj: dict[str, Any],
    line_no: int,
    source_format: str,
) -> AgentAction | SkippedRow:
    raw = json.dumps(obj, default=str)[:_MAX_RAW_ECHO]

    agent_id = _first(obj, _AGENT_KEYS)
    if not isinstance(agent_id, str) or not agent_id.strip():
        return SkippedRow(line_no, "no agent identifier", raw)

    capability = _normalize_capability(_first(obj, _CAPABILITY_KEYS))
    if capability is None:
        return SkippedRow(line_no, "no capability/tool name", raw)

    timestamp = parse_timestamp(_first(obj, _TIMESTAMP_KEYS))
    if timestamp is None:
        return SkippedRow(line_no, "no parseable timestamp", raw)

    request_id = _first(obj, _REQUEST_KEYS)
    raw_outcome = obj.get("outcome") or obj.get("status")
    outcome = _normalize_outcome(raw_outcome)

    context: dict[str, Any] = {
        "source_format": source_format,
        "source_line": line_no,
    }
    if raw_outcome is not None:
        # Preserve exactly what the source claimed.  `outcome` is a legacy
        # normalization and is not proof that dispatch or an effect occurred.
        context["reported_outcome"] = str(raw_outcome)

    return AgentAction(
        agent_id=agent_id.strip(),
        capability=capability,
        timestamp=timestamp,
        arguments=_coerce_arguments(_first(obj, _ARGUMENT_KEYS)),
        context=context,
        request_id=str(request_id) if request_id is not None else None,
        outcome=outcome,
    )


# ---------------------------------------------------------------------
# per-format extraction: log line -> zero or more flat dicts
# ---------------------------------------------------------------------


def _extract_mcp(obj: dict[str, Any]) -> list[dict[str, Any]]:
    """MCP JSON-RPC frame. Only tools/call carries an action; every
    other method (initialize, tools/list, notifications) is protocol
    chatter and is not an agent action."""
    if obj.get("method") != "tools/call":
        return []
    params = obj.get("params") or {}
    flat = dict(obj)
    flat.pop("params", None)
    flat["tool"] = params.get("name")
    flat["arguments"] = params.get("arguments")
    meta = params.get("_meta") or {}
    for key in _AGENT_KEYS:
        if key in meta:
            flat[key] = meta[key]
    return [flat]


def _extract_openai(obj: dict[str, Any]) -> list[dict[str, Any]]:
    """One chat-completion record may carry several tool_calls; each is
    a separate agent action."""
    calls: list[dict[str, Any]] = []
    choices = obj.get("choices") or []
    messages = [c.get("message", {}) for c in choices if isinstance(c, dict)]
    if "message" in obj and isinstance(obj["message"], dict):
        messages.append(obj["message"])
    if "tool_calls" in obj:
        messages.append(obj)

    for msg in messages:
        for call in msg.get("tool_calls") or []:
            fn = call.get("function") or {}
            flat = {k: v for k, v in obj.items() if k != "choices"}
            flat["tool"] = fn.get("name")
            flat["arguments"] = fn.get("arguments")
            flat["call_id"] = call.get("id")
            calls.append(flat)
    return calls


def _extract_anthropic(obj: dict[str, Any]) -> list[dict[str, Any]]:
    """Anthropic messages carry tool_use blocks in content."""
    calls: list[dict[str, Any]] = []
    content = obj.get("content")
    if isinstance(content, list):
        for block in content:
            if not isinstance(block, dict) or block.get("type") != "tool_use":
                continue
            flat = {k: v for k, v in obj.items() if k != "content"}
            flat["tool"] = block.get("name")
            flat["arguments"] = block.get("input")
            flat["call_id"] = block.get("id")
            calls.append(flat)
    return calls


def _extract_claude_code(obj: dict[str, Any]) -> list[dict[str, Any]]:
    """Claude Code / Cursor session lines nest the content array inside
    `message`, unlike the raw Anthropic API shape. Session identity comes
    from sessionId; the per-line uuid is the correlation id."""
    message = obj.get("message")
    if not isinstance(message, dict):
        return []
    content = message.get("content")
    if not isinstance(content, list):
        return []

    calls: list[dict[str, Any]] = []
    for block in content:
        if not isinstance(block, dict) or block.get("type") != "tool_use":
            continue
        flat = {k: v for k, v in obj.items() if k != "message"}
        flat["tool"] = block.get("name")
        flat["arguments"] = block.get("input")
        flat["call_id"] = block.get("id") or obj.get("uuid")
        calls.append(flat)
    return calls


def _extract_adr(obj: dict[str, Any]) -> list[dict[str, Any]]:
    """Uber ADR-Bench record: {type, task_id, conversation[], result{}}.

    The corpus identifies tasks, not agents, so no agent id exists in
    the data. Callers must supply one via ingest(agent_id=...); the
    substitution is recorded rather than invented here.
    """
    if obj.get("type") == "manifest":
        return []
    convo = obj.get("conversation")
    if not isinstance(convo, list):
        return []
    task = obj.get("task_id")
    res = obj.get("result") or {}
    ok = res.get("success")
    out: list[dict[str, Any]] = []
    for msg in convo:
        if not isinstance(msg, dict):
            continue
        for call in msg.get("tool_calls") or []:
            if not isinstance(call, dict):
                continue
            name = call.get("name")
            if not name:
                continue
            out.append(
                {
                    "capability": name,
                    "timestamp": msg.get("timestamp"),
                    "arguments": call.get("input") or call.get("arguments") or {},
                    "request_id": call.get("id"),
                    "outcome": "ok" if ok else ("error" if ok is False else None),
                    "task_id": task,
                }
            )
    return out


def _extract_generic(obj: dict[str, Any]) -> list[dict[str, Any]]:
    return [obj]


_EXTRACTORS = {
    "mcp": _extract_mcp,
    "openai": _extract_openai,
    "adr": _extract_adr,
    "anthropic": _extract_anthropic,
    "claude_code": _extract_claude_code,
    "generic": _extract_generic,
}


# ---------------------------------------------------------------------
# detection
# ---------------------------------------------------------------------


def _sample_lines(path: Path, limit: int = 50) -> list[str]:
    out: list[str] = []
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if line:
                out.append(line)
            if len(out) >= limit:
                break
    return out


def detect_format(path: str | Path) -> str:
    """Best-effort sniff. Returns a concrete format name, never 'auto'.

    Detection is a convenience, not a guarantee: it looks at up to 50
    lines and picks the shape that explains the most of them. Pass an
    explicit format when the answer matters.
    """
    path = Path(path)
    if path.suffix.lower() in (".db", ".sqlite", ".sqlite3"):
        return "sqlite"
    if path.suffix.lower() in (".csv", ".tsv"):
        return "csv"

    sample = _sample_lines(path)
    if not sample:
        return "generic"

    parsed: list[dict[str, Any]] = []
    for line in sample:
        try:
            obj = json.loads(line)
        except ValueError:
            continue
        if isinstance(obj, dict):
            parsed.append(obj)

    if not parsed:
        # Not JSONL. If the first line looks like a header, treat as CSV.
        if "," in sample[0]:
            return "csv"
        return "generic"

    scores = {
        "mcp": sum(1 for o in parsed if o.get("method") or "jsonrpc" in o),
        "openai": sum(1 for o in parsed if "choices" in o or "tool_calls" in o),
        "anthropic": sum(
            1
            for o in parsed
            if isinstance(o.get("content"), list)
            and any(
                isinstance(b, dict) and b.get("type") == "tool_use"
                for b in o["content"]
            )
        ),
        "claude_code": sum(
            1
            for o in parsed
            if isinstance(o.get("message"), dict)
            and isinstance(o["message"].get("content"), list)
            and any(
                isinstance(b, dict) and b.get("type") == "tool_use"
                for b in o["message"]["content"]
            )
        ),
    }
    best, score = max(scores.items(), key=lambda kv: kv[1])
    return best if score else "generic"


# ---------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------


def _iter_json_lines(path: Path) -> Iterator[tuple[int, str]]:
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        yield from enumerate(fh, start=1)


def _ingest_csv(path: Path, result: IngestResult) -> None:
    with path.open("r", encoding="utf-8", errors="replace", newline="") as fh:
        text = fh.read()
    if not text.strip():
        return
    try:
        dialect = _csv.Sniffer().sniff(text[:4096], delimiters=",;\t|")
    except _csv.Error:
        dialect = _csv.excel
    reader = _csv.DictReader(io.StringIO(text), dialect=dialect)
    for line_no, row in enumerate(reader, start=2):  # 1 is the header
        result.lines_read += 1
        clean = {k.strip(): v for k, v in row.items() if k}
        built = _build_action(clean, line_no, "csv")
        if isinstance(built, SkippedRow):
            result.skipped.append(built)
        else:
            result.actions.append(built)


def _ingest_sqlite(
    path: Path,
    agent_id: str | None,
    result: IngestResult,
) -> None:
    """Read PrivateVault's append-only records table without writing the DB."""
    uri = f"file:{path.resolve()}?mode=ro"
    try:
        connection = sqlite3.connect(uri, uri=True)
    except sqlite3.Error as exc:
        raise ValueError(f"cannot open SQLite history read-only: {exc}") from exc

    try:
        tables = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table'"
            )
        }
        if "records" not in tables:
            raise ValueError("SQLite history has no records table")

        columns = {row[1] for row in connection.execute("PRAGMA table_info(records)")}
        if not {"seq", "body"}.issubset(columns):
            raise ValueError("SQLite records table must contain seq and body")

        for line_no, (body,) in enumerate(
            connection.execute("SELECT body FROM records ORDER BY seq"),
            start=1,
        ):
            result.lines_read += 1
            try:
                obj = json.loads(body)
            except (TypeError, ValueError) as exc:
                result.skipped.append(
                    SkippedRow(
                        line_no,
                        f"invalid record body JSON: {str(exc)[:60]}",
                        str(body)[:_MAX_RAW_ECHO],
                    )
                )
                continue
            if not isinstance(obj, dict):
                result.skipped.append(
                    SkippedRow(
                        line_no,
                        "record body is not a JSON object",
                        str(body)[:_MAX_RAW_ECHO],
                    )
                )
                continue
            _ingest_row(obj, line_no, "sqlite", agent_id, result)
    except sqlite3.Error as exc:
        raise ValueError(f"cannot read SQLite history: {exc}") from exc
    finally:
        connection.close()


def _ingest_row(
    flat: dict[str, Any],
    line_no: int,
    resolved: str,
    agent_id: str | None,
    result: IngestResult,
) -> None:
    built = _build_action(flat, line_no, resolved)
    if (
        isinstance(built, SkippedRow)
        and built.reason == "no agent identifier"
        and agent_id
    ):
        retry = dict(flat)
        retry["agent_id"] = agent_id
        built = _build_action(retry, line_no, resolved)
        if isinstance(built, AgentAction):
            built.context["agent_id_supplied"] = True
    if isinstance(built, SkippedRow):
        result.skipped.append(built)
    else:
        result.actions.append(built)


def _ingest_jsonl(
    path: Path,
    resolved: str,
    agent_id: str | None,
    result: IngestResult,
) -> None:
    extract = _EXTRACTORS[resolved]
    for line_no, line in _iter_json_lines(path):
        stripped = line.strip()
        if not stripped:
            continue
        result.lines_read += 1
        try:
            obj = json.loads(stripped)
        except ValueError as exc:
            result.skipped.append(
                SkippedRow(
                    line_no,
                    f"invalid JSON: {exc.args[0][:60]}",
                    stripped[:_MAX_RAW_ECHO],
                )
            )
            continue
        if not isinstance(obj, dict):
            result.skipped.append(
                SkippedRow(
                    line_no, "line is not a JSON object", stripped[:_MAX_RAW_ECHO]
                )
            )
            continue
        # Protocol chatter in a well-formed log is expected and is not a
        # failure to understand it, so an empty extraction is not a skip.
        for flat in extract(obj):
            _ingest_row(flat, line_no, resolved, agent_id, result)


def ingest(
    path: str | Path,
    fmt: str = "auto",
    *,
    agent_id: str | None = None,
) -> IngestResult:
    """Read a log file into actions.

    agent_id is a LAST-RESORT override for logs that genuinely carry no
    identity (a single-agent stdio session, say). It is applied only to
    rows that would otherwise be skipped for that reason, and the
    substitution is recorded in the action's context so the report can
    say the identity was supplied rather than observed.
    """
    if fmt not in FORMATS:
        raise ValueError(f"unknown format {fmt!r}; expected one of {FORMATS}")

    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"no such log file: {path}")

    resolved = detect_format(path) if fmt == "auto" else fmt
    result = IngestResult(source_format=resolved, source_path=str(path))

    if resolved == "csv":
        _ingest_csv(path, result)
    elif resolved == "sqlite":
        _ingest_sqlite(path, agent_id, result)
    else:
        _ingest_jsonl(path, resolved, agent_id, result)
    return result


# ==================================================================
# from agent_dna/scan/inventory.py
# ==================================================================

# --- effect classes, ordered by how much they matter -------------------

IRREVERSIBLE = "IRREVERSIBLE"
MUTATING = "MUTATING"
READ_ONLY = "READ_ONLY"
UNKNOWN = "UNKNOWN"

EFFECTS = (IRREVERSIBLE, MUTATING, UNKNOWN, READ_ONLY)


@dataclass(frozen=True)
class Rule:
    """One classification rule. `pattern` matches a capability name."""

    pattern: str
    effect: str
    note: str

    def matches(self, capability: str) -> bool:
        return re.fullmatch(self.pattern, capability, re.IGNORECASE) is not None


# Exact capability contracts are authoritative for inventory classification.
# A capability name that is not listed here may still match one of the narrow
# legacy rules below, but ambiguous compound names remain UNKNOWN.  The
# registry is deliberately explicit: a namespace identifies a domain, not an
# effect, and token position is not reliable enough to infer safety.
CAPABILITY_MANIFEST_V1: dict[str, tuple[str, str]] = {
    "crm.read_contact": (READ_ONLY, "reads a CRM contact"),
    "crm.update_contact": (MUTATING, "changes a CRM contact"),
    "email.send": (IRREVERSIBLE, "sends a message externally"),
    "payments.drain_account": (IRREVERSIBLE, "moves money"),
    "payments.get_balance": (READ_ONLY, "reads financial state"),
    "payments.transfer": (IRREVERSIBLE, "moves money"),
    "settle.view_queue": (READ_ONLY, "reads a settlement queue"),
    "storage.bulk_export": (IRREVERSIBLE, "exports data from its current scope"),
    "tool_search": (UNKNOWN, "acquires new capabilities mid-session"),
    "web_search": (READ_ONLY, "retrieves remote content"),
    "wire.get_status": (READ_ONLY, "reads payment status"),
}


# MCP tools, keyed on the canonical <server>.<tool> form. Assigned by
# hand from observed contracts, same discipline as the manifest above:
# an unlisted MCP tool stays UNKNOWN.
MCP_MANIFEST_V1: dict[str, tuple[str, str]] = {
    "excel_toolkit.excel_write_cell": (MUTATING, "writes a spreadsheet cell"),
    "excel_toolkit.excel_add_sheet": (MUTATING, "adds a worksheet"),
    "excel_toolkit.excel_create_workbook": (MUTATING, "creates a workbook"),
    "word_toolkit.word_add_paragraph": (MUTATING, "writes document text"),
    "word_toolkit.word_add_heading": (MUTATING, "writes a document heading"),
    "word_toolkit.word_add_table": (MUTATING, "writes a document table"),
    "word_toolkit.word_add_page_break": (MUTATING, "changes document layout"),
    "word_toolkit.word_create_document": (MUTATING, "creates a document"),
    "ppt_toolkit.ppt_add_slide": (MUTATING, "adds a slide"),
    "ppt_toolkit.ppt_create_presentation": (MUTATING, "creates a presentation"),
    "sql_toolkit.insert_data": (MUTATING, "writes database rows"),
    "timeseries_db.write_points": (MUTATING, "writes time-series points"),
    "calendar_toolkit.add_event_to_calendar": (MUTATING, "creates a calendar event"),
    "scientific_calculator.basic_arithmetic": (READ_ONLY, "computes, no side effect"),
    "cloud_storage.upload_file": (IRREVERSIBLE, "sends data outside local scope"),
    "event_streaming.produce_message": (
        IRREVERSIBLE,
        "emits to a stream, not recallable",
    ),
    "cli_executor.exec": (UNKNOWN, "shell: effect depends on the command"),
    "file_server.write_file": (MUTATING, "writes a file"),
    "memory.create_entities": (MUTATING, "writes to a knowledge store"),
    "recipe_manager.create_recipe": (MUTATING, "creates a stored record"),
    "image_processor.analyze_image_properties": (READ_ONLY, "inspects an image"),
    "audio_processor.analyze_audio_file": (READ_ONLY, "inspects an audio file"),
    "sensor_data_processor.process_sensor_data": (
        READ_ONLY,
        "computes over sensor input",
    ),
    "sequential_thinking.sequentialthinking": (
        READ_ONLY,
        "reasoning step, no external effect",
    ),
    "ml_inference.predict": (READ_ONLY, "runs inference, no external effect"),
}


# Fallback rules cover only unambiguous, established spellings.  They never
# split compound names such as read_export or fetch_and_delete: without an
# exact manifest entry those names are UNKNOWN, never assumed safe.
DEFAULT_RULES: tuple[Rule, ...] = (
    # coding agents
    Rule(r"read|view|glob|grep|ls|cat|search", READ_ONLY, "reads only"),
    Rule(r"webfetch|websearch|fetch", READ_ONLY, "retrieves remote content"),
    Rule(r"todowrite|notebookread", READ_ONLY, "local scratch state"),
    Rule(
        r"write|edit|multiedit|notebookedit|create_file|str_replace",
        MUTATING,
        "writes to the filesystem",
    ),
    Rule(
        r"bash|shell|sh|exec|run_command|terminal",
        UNKNOWN,
        "shell: effect depends on the command",
    ),
    Rule(r"task|agent|dispatch.*", UNKNOWN, "delegates to another agent"),
    # Money-moving fallbacks require both a financial namespace and an
    # explicit money-moving operation.  payments.get_balance is not a write.
    Rule(
        r"(?:payment|payout|transfer|wire|settle|disburse)s?\."
        r"(?:execute|initiate|send|transfer|wire|remit|drain)(?:[_-].*)?",
        IRREVERSIBLE,
        "moves money",
    ),
    Rule(r"refund\.(issue|execute)|.*\.refund", IRREVERSIBLE, "issues a refund"),
    Rule(
        r".*\.(delete|destroy|purge|drop|revoke)",
        IRREVERSIBLE,
        "destroys data or access",
    ),
    Rule(r".*\.(publish|deploy|release)", IRREVERSIBLE, "publishes externally"),
    Rule(r".*\.(export|download|dump)", IRREVERSIBLE, "removes data from scope"),
    Rule(
        r".*\.(recommend|analyse|analyze|read|get|list|search)",
        READ_ONLY,
        "produces a recommendation or read",
    ),
    Rule(r".*\.(update|patch|set|create|write)", MUTATING, "changes stored state"),
)

# Shell command patterns, checked when a shell-like capability appears.
COMMAND_RULES: tuple[tuple[str, str, str], ...] = (
    (r"\bgit\s+push\b.*(--force|-f)\b", IRREVERSIBLE, "force-push rewrites history"),
    (r"\bgit\s+reset\s+--hard\b", IRREVERSIBLE, "discards work irrecoverably"),
    (
        r"\brm\s+(-[a-z]*r[a-z]*f|-[a-z]*f[a-z]*r)\b",
        IRREVERSIBLE,
        "recursive force delete",
    ),
    (r"\b(npm|yarn|pnpm)\s+publish\b", IRREVERSIBLE, "publishes a package"),
    (r"\bpip\s+.*\bupload\b|\btwine\s+upload\b", IRREVERSIBLE, "publishes a package"),
    (r"\bdocker\s+push\b", IRREVERSIBLE, "publishes an image"),
    (
        r"\b(kubectl|helm)\s+(apply|delete|upgrade)\b",
        IRREVERSIBLE,
        "changes a live cluster",
    ),
    (r"\bterraform\s+(apply|destroy)\b", IRREVERSIBLE, "changes live infrastructure"),
    (r"\bgh\s+(release|pr\s+merge)\b", IRREVERSIBLE, "publishes or merges"),
    (
        r"\bcurl\b.*(-X\s*(POST|PUT|DELETE|PATCH)|--data)",
        IRREVERSIBLE,
        "sends a state-changing request",
    ),
    (
        r"\bgit\s+(commit|add|checkout|merge|rebase)\b",
        MUTATING,
        "changes the repository",
    ),
    (r"\b(mv|cp|mkdir|touch|chmod|chown)\b", MUTATING, "changes the filesystem"),
    (
        r"\b(npm|yarn|pnpm|pip|apt|brew)\s+(install|add)\b",
        MUTATING,
        "installs dependencies",
    ),
    (
        r"\b(ls|cat|grep|find|head|tail|wc|git\s+(status|log|diff|show))\b",
        READ_ONLY,
        "reads only",
    ),
)

_SHELL_ARG_KEYS = ("command", "cmd", "script", "shell_command", "input")


def _canonical_mcp(capability: str) -> str | None:
    """`mcp__<server>__<tool>` -> `<server>.<tool>`, or None.

    This is parsing, not inference. MCP fixes the delimiter, so the
    split is lossless and reversible; the tool half may carry a leading
    underscore (mcp__excel_toolkit___excel_write_cell), which is noise
    from the server's own naming, not a segment. No effect is inferred
    here -- the result is only ever used as a manifest lookup key, so an
    unregistered tool stays UNKNOWN exactly as before.
    """
    if not capability.startswith("mcp__"):
        return None
    parts = capability.split("__")
    if len(parts) != 3:
        return None
    server, tool = parts[1].strip("_"), parts[2].strip("_")
    if not server or not tool:
        return None
    return f"{server}.{tool}"


@dataclass(frozen=True)
class Classification:
    effect: str
    basis: str  # "manifest" | "capability" | "command" | "default"
    note: str


def _command_text(action: AgentAction) -> str | None:
    for key in _SHELL_ARG_KEYS:
        value = action.arguments.get(key)
        if isinstance(value, str) and value.strip():
            return value
    return None


def _rank(effect: str) -> int:
    return EFFECTS.index(effect)


def _mcp_contract(capability: str) -> Classification | None:
    """Manifest lookup for an MCP-qualified name, or None."""
    canonical = _canonical_mcp(capability)
    if canonical is None:
        return None
    contract = MCP_MANIFEST_V1.get(canonical)
    if contract is None:
        return None
    effect, note = contract
    return Classification(effect, "manifest", note)


def classify(
    action: AgentAction,
    rules: tuple[Rule, ...] = DEFAULT_RULES,
    manifest: dict[str, tuple[str, str]] = CAPABILITY_MANIFEST_V1,
) -> Classification:
    """Classify from an exact contract, then narrow fallback rules.

    Command inspection remains authoritative for shell-like tools because
    `Bash` alone says nothing.  Unregistered compound names do not get token
    guessed into a safe class.
    """
    contract = manifest.get(action.capability.casefold())
    if contract is not None:
        effect, note = contract
        return Classification(effect, "manifest", note)

    mcp = _mcp_contract(action.capability)
    if mcp is not None:
        return mcp

    best: Classification | None = None
    for rule in rules:
        if not rule.matches(action.capability):
            continue
        cand = Classification(rule.effect, "capability", rule.note)
        if best is None or _rank(cand.effect) < _rank(best.effect):
            best = cand

    # A shell tool's name says nothing; the command says everything. When
    # a command rule matches it is authoritative and overrides the
    # capability-level guess in either direction -- `git status` under
    # Bash is read-only however alarming the tool name looks.
    command = _command_text(action)
    if command:
        for pattern, effect, note in COMMAND_RULES:
            if re.search(pattern, command, re.IGNORECASE):
                return Classification(effect, "command", note)

    if best is None:
        return Classification(UNKNOWN, "default", "capability not recognised")
    return best


# --- aggregation -------------------------------------------------------


@dataclass
class ToolUsage:
    """One capability, and the spread of effects it was used for.

    A shell tool is not one thing. `git status` and `git push --force`
    arrive under the same capability name, so a single label would
    overstate the finding. The per-effect counts are the honest answer;
    `worst` exists only for sorting.
    """

    capability: str
    count: int = 0
    agents: set[str] = field(default_factory=set)
    effects: dict[str, int] = field(default_factory=lambda: dict.fromkeys(EFFECTS, 0))
    notes: dict[str, str] = field(default_factory=dict)
    basis: str = "default"
    examples: list[str] = field(default_factory=list)

    def observe(self, action: AgentAction, cls: Classification) -> None:
        self.count += 1
        self.agents.add(action.agent_id)
        self.effects[cls.effect] += 1
        self.notes.setdefault(cls.effect, cls.note)
        if cls.basis == "command":
            self.basis = "command"
        elif cls.basis == "manifest" and self.basis != "command":
            self.basis = "manifest"
        elif self.basis == "default" and cls.basis == "capability":
            self.basis = "capability"
        if cls.effect == IRREVERSIBLE and len(self.examples) < 3:
            sample = _command_text(action) or _short_args(action)
            if sample and sample not in self.examples:
                self.examples.append(sample)

    @property
    def worst(self) -> str:
        """Strongest effect actually observed, not a guess about the tool."""
        for effect in EFFECTS:
            if self.effects.get(effect):
                return effect
        return UNKNOWN

    @property
    def irreversible(self) -> int:
        return self.effects.get(IRREVERSIBLE, 0)

    @property
    def note(self) -> str:
        return self.notes.get(self.worst, "")

    def spread(self) -> str:
        """e.g. '3 irreversible, 1 mutating, 1 read-only'"""
        parts = [
            f"{n} {e.lower().replace('_', '-')}"
            for e in EFFECTS
            if (n := self.effects.get(e, 0))
        ]
        return ", ".join(parts)


def _short_args(action: AgentAction, limit: int = 90) -> str:
    if not action.arguments:
        return ""
    text = ", ".join(f"{k}={v!r}" for k, v in list(action.arguments.items())[:3])
    return text if len(text) <= limit else text[: limit - 1] + "\u2026"


@dataclass
class AgentProfile:
    agent_id: str
    actions: int = 0
    capabilities: set[str] = field(default_factory=set)
    irreversible: int = 0
    mutating: int = 0
    unknown: int = 0
    read_only: int = 0
    first_seen: float | None = None
    last_seen: float | None = None

    @property
    def reach(self) -> int:
        """Distinct capabilities this agent demonstrably reached."""
        return len(self.capabilities)


@dataclass
class InventoryReport:
    source_path: str = ""
    source_format: str = ""
    lines_read: int = 0
    actions: int = 0
    coverage: float = 0.0
    skip_reasons: dict[str, int] = field(default_factory=dict)
    tools: dict[str, ToolUsage] = field(default_factory=dict)
    agents: dict[str, AgentProfile] = field(default_factory=dict)
    time_span: tuple[float, float] | None = None

    def by_effect(self) -> dict[str, int]:
        counts = dict.fromkeys(EFFECTS, 0)
        for usage in self.tools.values():
            for effect, n in usage.effects.items():
                counts[effect] += n
        return counts

    def irreversible_tools(self) -> list[ToolUsage]:
        return sorted(
            (t for t in self.tools.values() if t.irreversible),
            key=lambda t: -t.irreversible,
        )

    def widest_reach(self) -> list[AgentProfile]:
        return sorted(self.agents.values(), key=lambda a: (-a.reach, -a.irreversible))


def build_inventory(
    result: Any, rules: tuple[Rule, ...] = DEFAULT_RULES
) -> InventoryReport:
    """result: an IngestResult from agent_dna.scan.ingest."""
    report = InventoryReport(
        source_path=result.source_path,
        source_format=result.source_format,
        lines_read=result.lines_read,
        actions=result.understood,
        coverage=result.coverage,
        skip_reasons=result.skip_reasons(),
        time_span=result.time_span(),
    )

    per_agent: dict[str, AgentProfile] = defaultdict(lambda: AgentProfile(""))

    for action in result.actions:
        cls = classify(action, rules)

        usage = report.tools.get(action.capability)
        if usage is None:
            usage = ToolUsage(capability=action.capability)
            report.tools[action.capability] = usage
        usage.observe(action, cls)

        profile = per_agent[action.agent_id]
        if not profile.agent_id:
            profile.agent_id = action.agent_id
        profile.actions += 1
        profile.capabilities.add(action.capability)
        if cls.effect == IRREVERSIBLE:
            profile.irreversible += 1
        elif cls.effect == MUTATING:
            profile.mutating += 1
        elif cls.effect == UNKNOWN:
            profile.unknown += 1
        else:
            profile.read_only += 1
        ts = action.timestamp
        profile.first_seen = (
            ts if profile.first_seen is None else min(profile.first_seen, ts)
        )
        profile.last_seen = (
            ts if profile.last_seen is None else max(profile.last_seen, ts)
        )

    report.agents = dict(per_agent)
    return report


# ==================================================================
# from tools/pvscan.py
# ==================================================================

LOG_SUFFIXES = (".jsonl", ".json", ".log", ".ndjson", ".csv", ".tsv")
RECURSIVE_LOG_SUFFIXES = (".jsonl", ".log", ".ndjson")
RULE = "=" * 68
THIN = "-" * 68


def find_logs(target: Path, max_files: int) -> list[Path]:
    if target.is_file():
        return [target]
    if not target.is_dir():
        raise SystemExit(f"pvscan: no such file or directory: {target}")
    found = sorted(
        p
        for p in target.rglob("*")
        if p.is_file()
        and p.suffix.lower() in RECURSIVE_LOG_SUFFIXES
        and p.stat().st_size > 0
    )
    return found[:max_files]


class Totals:
    """Aggregate across many files without pretending they are one file."""

    def __init__(self) -> None:
        self.files_read = 0
        self.files_empty: list[str] = []
        self.lines = 0
        self.actions = 0
        self.skipped = 0
        self.skip_reasons: dict[str, int] = {}
        self.formats: dict[str, int] = {}
        self.tools: dict[str, object] = {}
        self.agents: dict[str, object] = {}
        self.span: tuple[float, float] | None = None
        self.reported_outcomes: dict[str, int] = {}

    def absorb(self, inv, result) -> None:
        self.files_read += 1
        self.lines += inv.lines_read
        self.actions += inv.actions
        self.skipped += len(result.skipped)
        self.formats[inv.source_format] = self.formats.get(inv.source_format, 0) + 1
        for reason, n in inv.skip_reasons.items():
            self.skip_reasons[reason] = self.skip_reasons.get(reason, 0) + n
        if inv.actions == 0:
            self.files_empty.append(inv.source_path)

        for action in result.actions:
            reported = action.context.get("reported_outcome", "not_reported")
            label = str(reported).strip().lower() or "not_reported"
            self.reported_outcomes[label] = self.reported_outcomes.get(label, 0) + 1

        for name, usage in inv.tools.items():
            existing = self.tools.get(name)
            if existing is None:
                self.tools[name] = usage
                continue
            existing.count += usage.count
            existing.agents |= usage.agents
            for effect, n in usage.effects.items():
                existing.effects[effect] += n
            for effect, note in usage.notes.items():
                existing.notes.setdefault(effect, note)
            if usage.basis == "command":
                existing.basis = "command"
            for example in usage.examples:
                if example not in existing.examples and len(existing.examples) < 3:
                    existing.examples.append(example)

        for aid, profile in inv.agents.items():
            existing = self.agents.get(aid)
            if existing is None:
                self.agents[aid] = profile
                continue
            existing.actions += profile.actions
            existing.capabilities |= profile.capabilities
            existing.irreversible += profile.irreversible
            existing.mutating += profile.mutating
            existing.unknown += profile.unknown
            existing.read_only += profile.read_only

        if inv.time_span:
            lo, hi = inv.time_span
            self.span = (
                (lo, hi)
                if self.span is None
                else (min(self.span[0], lo), max(self.span[1], hi))
            )

    @property
    def coverage(self) -> float:
        total = self.actions + self.skipped
        return (self.actions / total) if total else 0.0

    def by_effect(self) -> dict[str, int]:
        counts = dict.fromkeys(EFFECTS, 0)
        for usage in self.tools.values():
            for effect, n in usage.effects.items():
                counts[effect] += n
        return counts


def _ts(value: float | None) -> str:
    if value is None:
        return "-"
    return datetime.fromtimestamp(value, UTC).strftime("%Y-%m-%d %H:%M UTC")


def render(t: Totals, target: Path, top_agents: int = 15) -> str:
    out: list[str] = []
    add = out.append

    add(RULE)
    add("pv scan -- AGENT ACTION INVENTORY")
    add(RULE)
    add(f"Source            {target}")
    fmt = ", ".join(f"{k} x{v}" for k, v in sorted(t.formats.items()))
    add(f"Files read        {t.files_read}   ({fmt or 'none'})")
    add(f"Lines             {t.lines}")
    add(f"Actions parsed    {t.actions}   coverage {t.coverage:.0%}")
    if t.span:
        add(f"Window            {_ts(t.span[0])}  ->  {_ts(t.span[1])}")
    add(f"Agents / sessions {len(t.agents)}")
    add(f"Distinct tools    {len(t.tools)}")
    if t.reported_outcomes:
        outcomes = ", ".join(
            f"{name} {count}" for name, count in sorted(t.reported_outcomes.items())
        )
        add(f"Source outcomes   {outcomes}")
        add("                  Source labels only; not execution proof.")
    add("")

    counts = t.by_effect()
    add("EFFECT DISTRIBUTION")
    add(THIN)
    for effect in EFFECTS:
        n = counts[effect]
        pct = (n / t.actions * 100) if t.actions else 0.0
        bar = "#" * int(pct / 2.5)
        add(f"  {effect:14} {n:6}  {pct:5.1f}%  {bar}")
    add("")

    add("TOOLS OBSERVED")
    add(THIN)
    ordered = sorted(
        t.tools.values(),
        key=lambda u: (EFFECTS.index(u.worst), -u.count),
    )
    for usage in ordered[:25]:
        add(f"  {usage.capability:22} x{usage.count:<5} {usage.worst}")
        add(f"      {usage.spread()}   ({usage.basis}) {usage.note}")
        for example in usage.examples:
            add(f"      e.g. {example[:80]}")
    add("")

    irreversible = [u for u in ordered if u.irreversible]
    add("IRREVERSIBLE ACTIONS")
    add(THIN)
    if not irreversible:
        add("  None observed in this window.")
    else:
        total = sum(u.irreversible for u in irreversible)
        add(f"  {total} observed attempt(s) classified irreversible if executed.")
        add("  This inventory does not prove dispatch or a real-world effect.")
        for usage in irreversible:
            who = ", ".join(sorted(usage.agents)[:3])
            add(f"    {usage.capability:20} x{usage.irreversible:<4} by {who}")
    add("")

    add("OBSERVED ATTEMPTS BY AGENT")
    add(THIN)
    ranked = sorted(
        t.agents.values(), key=lambda a: (-a.irreversible, -len(a.capabilities))
    )
    add(
        f"  {'agent / session':30} {'acts':>5} {'tools':>6} {'irrev':>6} {'unknown':>8}"
    )
    for profile in ranked[:top_agents]:
        add(
            f"  {profile.agent_id[:30]:30} {profile.actions:5} "
            f"{len(profile.capabilities):6} {profile.irreversible:6} {profile.unknown:8}"
        )
    if len(ranked) > top_agents:
        rest = ranked[top_agents:]
        add(
            f"  ... and {len(rest)} more, {sum(1 for a in rest if a.irreversible)} "
            f"of which reached an irreversible action (full list in --json)"
        )
    add("")

    unknown_tools = [u for u in ordered if u.effects.get(UNKNOWN)]
    if unknown_tools:
        add("UNCLASSIFIED")
        add(THIN)
        add("  Not recognised, so not assumed safe. Worth a human look.")
        for usage in unknown_tools:
            add(f"    {usage.capability:22} x{usage.effects[UNKNOWN]}")
        add("")

    add("AUTHORITY EVIDENCE")
    add(THIN)
    add("  Not assessed by this dependency-free inventory command.")
    add("  Run `pv authority scan` with a pinned trust bundle to classify")
    add("  evidence as VERIFIED, INVALID, UNVERIFIABLE, or ABSENT.")
    add("")

    if t.skip_reasons:
        add("LINES NOT UNDERSTOOD")
        add(THIN)
        for reason, n in sorted(t.skip_reasons.items(), key=lambda kv: -kv[1]):
            add(f"    {n:6}  {reason}")
        add("")

    if t.files_empty:
        add(f"  {len(t.files_empty)} file(s) yielded no actions. First few:")
        for path in t.files_empty[:3]:
            add(f"    {path}")
        add("")

    add(RULE)
    add("Read-only. No data transmitted. Reports are written locally")
    add("only when requested.")
    add(RULE)
    return "\n".join(out)


def to_json(t: Totals, target: Path) -> dict:
    return {
        "spec": "pv-scan-inventory/0.1",
        "source": str(target),
        "files_read": t.files_read,
        "lines": t.lines,
        "actions": t.actions,
        "coverage": round(t.coverage, 4),
        "formats": t.formats,
        "window": [_ts(t.span[0]), _ts(t.span[1])] if t.span else None,
        "effects": t.by_effect(),
        "tools": [
            {
                "capability": u.capability,
                "count": u.count,
                "worst": u.worst,
                "effects": u.effects,
                "basis": u.basis,
                "agents": sorted(u.agents),
                "examples": u.examples,
            }
            for u in sorted(
                t.tools.values(), key=lambda u: (EFFECTS.index(u.worst), -u.count)
            )
        ],
        "agents": [
            {
                "agent_id": a.agent_id,
                "actions": a.actions,
                "reach": len(a.capabilities),
                "irreversible": a.irreversible,
                "mutating": a.mutating,
                "unknown": a.unknown,
                "read_only": a.read_only,
            }
            for a in sorted(t.agents.values(), key=lambda a: -a.irreversible)
        ],
        "authority_evidence_assessed": False,
        "reported_outcomes": t.reported_outcomes,
        "skip_reasons": t.skip_reasons,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="pvscan",
        description="Read-only inventory of what agents in a log can do.",
    )
    parser.add_argument("path", help="log file, or directory to search recursively")
    parser.add_argument(
        "--format",
        default="auto",
        choices=FORMATS,
        help="override log format detection",
    )
    parser.add_argument("--json", metavar="OUT", help="also write a JSON report")
    parser.add_argument(
        "--max-files",
        type=int,
        default=500,
        help="stop after this many files (default 500)",
    )
    parser.add_argument(
        "--agent-id", default=None, help="identity for logs that carry none"
    )
    parser.add_argument(
        "--top",
        type=int,
        default=15,
        help="agents to list before summarising (default 15)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="list the files that would be read, then stop",
    )
    args = parser.parse_args(argv)

    target = Path(args.path).expanduser()
    logs = find_logs(target, args.max_files)
    if not logs:
        print(f"pvscan: no log files found under {target}")
        return 1

    if args.dry_run:
        print(f"pvscan --dry-run: {len(logs)} file(s) would be read")
        for path in logs:
            print(f"  {path}")
        return 0

    totals = Totals()
    failures: list[tuple[Path, str]] = []
    for path in logs:
        try:
            result = ingest(path, args.format, agent_id=args.agent_id)
        except Exception as exc:  # a bad file must not kill the scan
            failures.append((path, f"{type(exc).__name__}: {exc}"))
            continue
        totals.absorb(build_inventory(result), result)

    print(render(totals, target, top_agents=args.top))

    if failures:
        print("FILES THAT COULD NOT BE READ")
        print(THIN)
        for path, why in failures[:10]:
            print(f"  {path}: {why}")
        print()

    if args.json:
        Path(args.json).write_text(
            json.dumps(to_json(totals, target), indent=2), encoding="utf-8"
        )
        print(f"JSON written to {args.json}")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BrokenPipeError:  # piped into head/less; not an error
        import os

        os.dup2(os.open(os.devnull, os.O_WRONLY), sys.stdout.fileno())
        raise SystemExit(0) from None
