#!/usr/bin/env python3
"""Build a single-file, dependency-free pvscan from repository sources.

The scan path touches only trace/ingest/inventory, all of which are
stdlib-only, so the whole tool flattens into one readable file. Readable
matters: the people we hand this to should be able to audit it before
they run it against their own logs.
"""

from __future__ import annotations

import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "distributions" / "pvscan.py"

SOURCES = [
    ("agent_dna/trace.py", None),
    ("agent_dna/scan/ingest.py", None),
    ("agent_dna/scan/inventory.py", None),
    ("tools/pvscan.py", None),
]

DROP_IMPORT = re.compile(
    r"^\s*from\s+\.{1,2}[\w.]*\s+import|^\s*from\s+agent_dna[\w.]*\s+import"
)
IMPORT_LINE = re.compile(r"^(?:import\s+\S|from\s+(?!\.)(?!agent_dna)\S+\s+import\s)")

STRIP_BEGIN = "# --- BEGIN STANDALONE-STRIP ---"
STRIP_END = "# --- END STANDALONE-STRIP ---"


def strip_marked_blocks(text: str) -> str:
    """Remove regions the source explicitly marks as repo-only.

    Guessing which imports to delete leaves broken try/except shells.
    The source says what to drop; the builder obeys.
    """
    out: list[str] = []
    skipping = False
    for line in text.splitlines():
        if line.strip() == STRIP_BEGIN:
            skipping = True
            continue
        if line.strip() == STRIP_END:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    return "\n".join(out)


def strip_module(text: str) -> tuple[list[str], list[str]]:
    """Return (import lines, body lines) with intra-package imports removed."""
    text = strip_marked_blocks(text)
    imports: list[str] = []
    body: list[str] = []
    lines = text.splitlines()
    i = 0
    if lines and lines[0].startswith("#!"):
        i = 1
    if i < len(lines) and lines[i].lstrip().startswith(('"""', "'''")):
        quote = lines[i].lstrip()[:3]
        if lines[i].count(quote) >= 2 and len(lines[i].strip()) > 3:
            i += 1
        else:
            i += 1
            while i < len(lines) and quote not in lines[i]:
                i += 1
            i += 1

    in_dropped = False
    for line in lines[i:]:
        if in_dropped:
            if line.rstrip().endswith(")"):
                in_dropped = False
            continue
        if DROP_IMPORT.match(line):
            if "(" in line and ")" not in line:
                in_dropped = True
            continue
        if line.startswith("from __future__"):
            continue
        if IMPORT_LINE.match(line):
            imports.append(line.rstrip())
            continue
        body.append(line.rstrip())
    return imports, body


def build() -> str:
    commit = "unknown"
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except Exception:
        pass

    all_imports: list[str] = []
    chunks: list[str] = []

    for rel, _ in SOURCES:
        path = ROOT / rel
        imports, body = strip_module(path.read_text(encoding="utf-8"))
        for imp in imports:
            if imp not in all_imports:
                all_imports.append(imp)
        while body and not body[0].strip():
            body.pop(0)
        while body and not body[-1].strip():
            body.pop()
        chunks.append(f"# {'=' * 66}\n# from {rel}\n# {'=' * 66}\n\n" + "\n".join(body))

    header = f'''#!/usr/bin/env python3
"""pvscan -- read-only inventory of what AI agents in a log can do.

Single file. No installation, no dependencies beyond the Python standard
library, no network access. It reads the paths you give it and writes
nothing except the report you ask for.

    python3 pvscan.py ~/.claude/projects/
    python3 pvscan.py session.jsonl --json report.json
    python3 pvscan.py ~/.claude/projects/ --dry-run    # list files, read none

Built from privatevault-agent-dna @ {commit} on {datetime.now(UTC).date().isoformat()}.
Generated by tools/build_pvscan_standalone.py -- edit the sources, not this.

PrivateVault AI. Read it before you run it; that is the point of one file.
"""

from __future__ import annotations

'''

    return header + "\n".join(sorted(set(all_imports))) + "\n\n\n" + "\n\n\n".join(chunks) + "\n"


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    OUT.chmod(0o755)

    # The generated file must pass the same lint as hand-written source.
    # Flattening reorders imports and can orphan one, so fix in place
    # rather than shipping something that fails our own pre-commit.
    for args in (["check", "--fix", "--quiet"], ["format", "--quiet"]):
        try:
            subprocess.run(
                [sys.executable, "-m", "ruff", *args, str(OUT)],
                cwd=ROOT, check=False, capture_output=True,
            )
        except Exception:
            print("warning: ruff unavailable; generated file not linted")
            break
    lines = len(OUT.read_text().splitlines())
    print(f"built {OUT}  ({lines} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
